spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rest_with_spring_boot_udemy?useTimezone=true&serverTimezone=UTC
    username: udemy
    password: GGss4840
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: false