cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://erudio.com.br
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rest_with_spring_boot_udemy?useTimezone=true&serverTimezone=UTC
    username: udemy
    password: GGss4840
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: false
springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true
